apiVersion: v1
kind: PersistentVolume
metadata:
  name: jmeter-volume
  labels:
    type: local
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/etc/jmeter"

