apiVersion: v1
kind: Pod
metadata:
  name: jmp
  namespace: iedi-apis
spec:
  volumes:
    - name: jmeter-storage
      persistentVolumeClaim:
        claimName: jmeter-claim
  containers:
    - name: jmeter-container
#      image: nginx
      image: test/jmeter
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/etc/jmeter"
          name: jmeter-storage
