apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jmeter-claim
  namespace: iedi-apis
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
